pacman -S deepin-file-manager
pacman -S firefox
pacman -S deepin-boot-maker
pacman -S deepin-terminal
pacman -S discord
pacman -S cairo-dock
pacman -S deepin-calculator
pacman -S vlc
pacman -S brave
pacman -S mesa
pacman -S xorg
pacman -S xorg-server
pacman -S xorg-apps
pacman -S xorg-drivers
pacman -S xorg-xkill
pacman -S xorg-xinit
pacman -S xterm
pacman -S plasma-desktop
pacman -S alsa-plugins
pacman -S alsa-utils
pacman -S ark
pacman -S audiocd-kio
pacman -S autoconf
pacman -S automake
pacman -S awesome-terminal-fonts
pacman -S base
pacman -S bash-completion
pacman -S bind
pacman -S binutils
pacman -S bison
pacman -S bluedevil
pacman -S bluez
pacman -S bluez-libs
pacman -S bluez-utils
pacman -S breeze
pacman -S breeze-gtk
pacman -S bridge-utils
pacman -S btrfs-progs
pacman -S celluloid
pacman -S cmatrix
pacman -S code
pacman -S cronie
pacman -S cups
pacman -S dialog
pacman -S discover
pacman -S dolphin
pacman -S dosfstools
pacman -S dtc
pacman -S efibootmgr
pacman -S egl-wayland
pacman -S exfat-utils
pacman -S extra-cmake-modules
pacman -S filelight
pacman -S flex
pacman -S fuse2
pacman -S fuse3
pacman -S fuseiso
pacman -S gamemode
pacman -S gcc
pacman -S gimp
pacman -S git
pacman -S gparted
pacman -S gptfdisk
pacman -S grub
pacman -S grub-customizer
pacman -S gst-libav
pacman -S gst-plugins-good
pacman -S gst-plugins-ugly
pacman -S gwenview
pacman -S haveged
pacman -S htop
pacman -S iptables-nft
pacman -S jdk-openjdk
pacman -S kate
pacman -S kcodecs
pacman -S kcoreaddons
pacman -S kde-plasma-addons
pacman -S kinfocenter
pacman -S kscreen
pacman -S kvantum-qt5
pacman -S kde-gtk-config
pacman -S kitty
pacman -S konsole
pacman -S kscreen
pacman -S layer-shell-qt
pacman -S libdvdcss
pacman -S libnewt
pacman -S libtool
pacman -S linux
pacman -S linux-firmware
pacman -S linux-headers
pacman -S lsof
pacman -S lutris
pacman -S lzop
pacman -S m4
pacman -S make
pacman -S milou
pacman -S nano
pacman -S neofetch
pacman -S networkmanager
pacman -S noto-fonts-emoji
pacman -S ntfs-3g
pacman -S ntp
pacman -S okular
pacman -S openbsd-netcat
pacman -S openssh
pacman -S os-prober
pacman -S oxygen
pacman -S p7zip
pacman -S pacman-contrib
pacman -S papirus-icon-theme
pacman -S patch
pacman -S picom
pacman -S pkgconf
pacman -S plasma-nm
pacman -S plasma-pa
pacman -S powerdevil
pacman -S powerline-fonts
pacman -S print-manager
pacman -S pulseaudio
pacman -S pulseaudio-alsa
pacman -S pulseaudio-bluetooth
pacman -S python-notify2
pacman -S python-psutil
pacman -S python-pyqt5
pacman -S python-pip
pacman -S qemu
pacman -S rsync
pacman -S sddm
pacman -S sddm-kcm
pacman -S snapper
pacman -S snap-pac
pacman -S spectacle
pacman -S steam
pacman -S sudo
pacman -S swtpm
pacman -S synergy
pacman -S systemsettings
pacman -S terminus-font
pacman -S traceroute
pacman -S ttf-droid
pacman -S ttf-hack
pacman -S ttf-roboto
pacman -S ufw
pacman -S unrar
pacman -S unzip
pacman -S usbutils
pacman -S vim
pacman -S virt-manager
pacman -S virt-viewer
pacman -S wget
pacman -S which
pacman -S wine-gecko
pacman -S wine-mono
pacman -S winetricks
pacman -S xdg-desktop-portal-kde
pacman -S xdg-user-dirs
pacman -S zeroconf-ioslave
pacman -S zip
pacman -S zsh
pacman -S zsh-syntax-highlighting
pacman -S zsh-autosuggestionspacman -S
echo if you want a full experenxe enable the glasy theme and open cairo dock all files on the desktop
reboot
